# -*- coding: utf-8 -*-
"""ejercicio3_subarray_maximo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IKIYp5ADat_hryx6AFLSJDXCoJm2Tm7n
"""

import time
import random
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns

# Fuerza bruta
def max_subarray_bruteforce(arr):
    max_sum = float('-inf')
    n = len(arr)
    for i in range(n):
        current_sum = 0
        for j in range(i, n):
            current_sum += arr[j]
            if current_sum > max_sum:
                max_sum = current_sum
    return max_sum


#Divide y vencerás
def max_crossing_sum(arr, left, mid, right):
    left_sum = float('-inf')
    total = 0
    for i in range(mid, left - 1, -1):
        total += arr[i]
        left_sum = max(left_sum, total)

    right_sum = float('-inf')
    total = 0
    for i in range(mid + 1, right + 1):
        total += arr[i]
        right_sum = max(right_sum, total)

    return left_sum + right_sum


def max_subarray_divide_conquer(arr, left, right):
    if left == right:
        return arr[left]
    mid = (left + right) // 2
    left_max  = max_subarray_divide_conquer(arr, left, mid)
    right_max = max_subarray_divide_conquer(arr, mid + 1, right)
    cross_max = max_crossing_sum(arr, left, mid, right)
    return max(left_max, right_max, cross_max)


#Verificación
A1 = [1, -7, 7, -1, 4, -7, 7, -5, 6, -7]
print("  Cédula: 1001470567")
print(f"  Arreglo: {A1}")
print(f"  Fuerza bruta:       suma = {max_subarray_bruteforce(A1)}")
print(f"  Divide y vencerás:  suma = {max_subarray_divide_conquer(A1, 0, len(A1)-1)}")


#Medición de tiempos
def measure_times(sizes, repetitions=50):
    brute_times = []
    divide_times = []

    for n in sizes:
        arr = [random.randint(-100, 100) for _ in range(n)]

        # Fuerza bruta
        total = 0
        for _ in range(repetitions):
            start = time.perf_counter()
            max_subarray_bruteforce(arr)
            total += time.perf_counter() - start
        brute_times.append(total / repetitions)

        # Divide y vencerás
        total = 0
        for _ in range(repetitions):
            start = time.perf_counter()
            max_subarray_divide_conquer(arr, 0, n - 1)
            total += time.perf_counter() - start
        divide_times.append(total / repetitions)

        print(f"n={n:5d} | Bruta: {brute_times[-1]*1000:.4f} ms "
              f"| Divide: {divide_times[-1]*1000:.4f} ms")

    return brute_times, divide_times


sizes = [10, 50, 100, 200, 500, 1000]
brute_times, divide_times = measure_times(sizes)


#Gráfica
sns.set_theme(style="whitegrid")

fig, axes = plt.subplots(1, 2, figsize=(14, 6))

brute_ms  = [t * 1000 for t in brute_times]
divide_ms = [t * 1000 for t in divide_times]

# Gráfica normal
axes[0].plot(sizes, brute_ms, marker='o', linewidth=2, label='Fuerza bruta O(n²)')
axes[0].plot(sizes, divide_ms, marker='s', linewidth=2, label='Divide y vencerás O(n log n)')
axes[0].set_xlabel('Tamaño de entrada (n)')
axes[0].set_ylabel('Tiempo promedio (ms)')
axes[0].set_title('Tiempo vs n')
axes[0].legend()
axes[0].grid(True)

# Gráfica log
axes[1].plot(sizes, brute_ms, marker='o', linewidth=2, label='Fuerza bruta')
axes[1].plot(sizes, divide_ms, marker='s', linewidth=2, label='Divide y vencerás')
axes[1].set_xlabel('Tamaño de entrada')
axes[1].set_ylabel('Tiempo promedio (ms)')
axes[1].set_title('Escala logarítmica')
axes[1].set_yscale('log')
axes[1].legend()
axes[1].grid(True)

plt.tight_layout()
plt.show()