# -*- coding: utf-8 -*-
"""ejercicio4_merge_vs_insertion_sort.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HIuOo1fuke-fwVoecHMhyX5OZzZeIExw
"""

import time
import random
import matplotlib.pyplot as plt
import seaborn as sns

#Insertion sort
def insertion_sort(arr):
    arr = arr.copy()
    for i in range(1, len(arr)):
        key = arr[i]
        j = i - 1
        while j >= 0 and arr[j] > key:
            arr[j + 1] = arr[j]
            j -= 1
        arr[j + 1] = key
    return arr


# Merge sort
def merge_sort(arr):
    if len(arr) <= 1:
        return arr

    mid = len(arr) // 2
    left  = merge_sort(arr[:mid])
    right = merge_sort(arr[mid:])
    return merge(left, right)


def merge(left, right):
    result = []
    i = j = 0
    while i < len(left) and j < len(right):
        if left[i] <= right[j]:
            result.append(left[i])
            i += 1
        else:
            result.append(right[j])
            j += 1
    result.extend(left[i:])
    result.extend(right[j:])
    return result


#Verificacion
A2 = [1, 7, 7, 1, 4, 7, 7, 5, 6, 7]
print("  Cédula: 1001470567")
print(f"  Arreglo original: {A2}")
print(f"  Insertion Sort:   {insertion_sort(A2)}")
print(f"  Merge Sort:       {merge_sort(A2)}")
print(f"  Resultados iguales: {insertion_sort(A2) == merge_sort(A2)}")

#Medición de tiempos
def measure_times(sizes, repetitions=50):
    insertion_times = []
    merge_times = []

    for n in sizes:
        arr = [random.randint(-100, 100) for _ in range(n)]

        # Insertion Sort
        total = 0
        for _ in range(repetitions):
            start = time.perf_counter()
            insertion_sort(arr)
            total += time.perf_counter() - start
        insertion_times.append((total / repetitions) * 1000)

        # Merge Sort
        total = 0
        for _ in range(repetitions):
            start = time.perf_counter()
            merge_sort(arr)
            total += time.perf_counter() - start
        merge_times.append((total / repetitions) * 1000)

        print(f"  n={n:5d} | Insertion Sort: {insertion_times[-1]:.4f} ms "
              f"| Merge Sort: {merge_times[-1]:.4f} ms")

    return insertion_times, merge_times


sizes = [10, 50, 100, 500, 1000, 5000]
insertion_times, merge_times = measure_times(sizes)


# Gráfica
sns.set_theme(style="whitegrid")
fig, axes = plt.subplots(1, 2, figsize=(14, 6))
colors = {"insertion": "#534AB7", "merge": "#1D9E75"}

# Gráfica 1: escala normal
axes[0].plot(sizes, insertion_times, marker='o', linewidth=2,
             color=colors["insertion"], label="Insertion Sort")
axes[0].plot(sizes, merge_times,     marker='s', linewidth=2,
             color=colors["merge"],     label="Merge Sort")
axes[0].set_xlabel("Tamaño de entrada (n)")
axes[0].set_ylabel("Tiempo promedio (ms)")
axes[0].set_title("Tiempo vs n")
axes[0].legend()
axes[0].set_xticks(sizes)
axes[0].tick_params(axis='x', rotation=30)
axes[0].grid(True)

# Gráfica 2: escala logarítmica
axes[1].plot(sizes, insertion_times, marker='o', linewidth=2,
             color=colors["insertion"], label="Insertion Sort")
axes[1].plot(sizes, merge_times,     marker='s', linewidth=2,
             color=colors["merge"],     label="Merge Sort")
axes[1].set_xlabel("Tamaño de entrada (n)")
axes[1].set_ylabel("Tiempo promedio (ms) — escala log")
axes[1].set_title("Escala logarítmica")
axes[1].set_yscale("log")
axes[1].legend()
axes[1].set_xticks(sizes)
axes[1].tick_params(axis='x', rotation=30)
axes[1].grid(True)

plt.tight_layout()
plt.show()